# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from add import Ui_AddUser
from dell import Ui_DeleteUser
from search import Ui_SearchUser
class Ui_BiometricVoice(object):
    def openAddUser(self):
        self.windows = QtWidgets.QWidget()
        self.ui = Ui_AddUser()
        self.ui.setupUi(self.windows)
        self.windows.show()

    def openSearchUser(self):
        self.windows = QtWidgets.QWidget()
        self.ui = Ui_SearchUser()
        self.ui.setupUi(self.windows)
        self.windows.show()

    def openDeleteUser(self):
        self.windows = QtWidgets.QWidget()
        self.ui = Ui_DeleteUser()
        self.ui.setupUi(self.windows)
        self.windows.show()

    def setupUi(self, BiometricVoice):
        BiometricVoice.setObjectName("BiometricVoice")
        BiometricVoice.resize(600, 250)
        BiometricVoice.setMinimumSize(QtCore.QSize(600, 250))
        BiometricVoice.setMaximumSize(QtCore.QSize(600, 250))
        BiometricVoice.setStyleSheet("QMainWindows{\n"
"    background-color:   rgb(47, 48, 50);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(BiometricVoice)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color:   rgb(0,0,0);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_user = QtWidgets.QFrame(self.centralwidget)
        self.add_user.setStyleSheet("QFrame{\n"
"    background-color:  rgb(56,58, 86);\n"
"}\n"
"")
        self.add_user.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_user.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_user.setObjectName("add_user")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.add_user)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ICON_A = QtWidgets.QFrame(self.add_user)
        self.ICON_A.setMinimumSize(QtCore.QSize(175, 175))
        self.ICON_A.setMaximumSize(QtCore.QSize(16777215, 200))
        self.ICON_A.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}\n"
"")
        self.ICON_A.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ICON_A.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ICON_A.setObjectName("ICON_A")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ICON_A)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.push_addUser = QtWidgets.QPushButton(self.ICON_A)

        self.push_addUser.clicked.connect(self.openAddUser)

        self.push_addUser.setStyleSheet("QPushButton{\n"
"border: 0px;\n"
"background-color:  rgb(56, 58, 86);\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:15px;\n"
"    background-color:  rgb(255, 243, 142);    \n"
"}")
        self.push_addUser.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/627121-200.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.push_addUser.setIcon(icon)
        self.push_addUser.setIconSize(QtCore.QSize(175, 175))
        self.push_addUser.setAutoDefault(False)
        self.push_addUser.setDefault(False)
        self.push_addUser.setObjectName("push_addUser")
        self.horizontalLayout_4.addWidget(self.push_addUser)
        self.verticalLayout.addWidget(self.ICON_A)
        self.frame_2 = QtWidgets.QFrame(self.add_user)
        self.frame_2.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("QLabel{\n"
"color: rgb(28,191,255);\n"
"}")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.add_user)
        self.search_user = QtWidgets.QFrame(self.centralwidget)
        self.search_user.setStyleSheet("QFrame{\n"
"    background-color:  rgb(56, 58, 86);\n"
"}")
        self.search_user.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_user.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_user.setObjectName("search_user")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.search_user)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ICON_S_2 = QtWidgets.QFrame(self.search_user)
        self.ICON_S_2.setStyleSheet("QFrame{\n"
"border: 0px;\n"
"}\n"
"")
        self.ICON_S_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ICON_S_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ICON_S_2.setObjectName("ICON_S_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ICON_S_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.push_searchUser = QtWidgets.QPushButton(self.ICON_S_2)

        self.push_searchUser.clicked.connect(self.openSearchUser)

        self.push_searchUser.setStyleSheet("QPushButton{\n"
"border: 0px;\n"
"background-color:  rgb(56, 58, 86);\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:15px;\n"
"    background-color:  rgb(255, 243, 142);    \n"
"}")
        self.push_searchUser.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/1425923-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.push_searchUser.setIcon(icon1)
        self.push_searchUser.setIconSize(QtCore.QSize(175, 175))
        self.push_searchUser.setObjectName("push_searchUser")
        self.horizontalLayout_5.addWidget(self.push_searchUser)
        self.verticalLayout_2.addWidget(self.ICON_S_2)
        self.frame_3 = QtWidgets.QFrame(self.search_user)
        self.frame_3.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(28,191,255);\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.search_user)
        self.dell_user = QtWidgets.QFrame(self.centralwidget)
        self.dell_user.setStyleSheet("QFrame{\n"
"    background-color:  rgb(56, 58, 86);\n"
"}")
        self.dell_user.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dell_user.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dell_user.setObjectName("dell_user")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dell_user)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ICON_S = QtWidgets.QFrame(self.dell_user)
        self.ICON_S.setStyleSheet("QFrame{\n"
"border: 0px;\n"
"}\n"
"\n"
"")
        self.ICON_S.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ICON_S.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ICON_S.setObjectName("ICON_S")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.ICON_S)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.push_deleteUser = QtWidgets.QPushButton(self.ICON_S)

        self.push_deleteUser.clicked.connect(self.openDeleteUser)

        self.push_deleteUser.setStyleSheet("QPushButton{\n"
"border: 0px;\n"
"background-color:  rgb(56, 58, 86);\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:15px;\n"
"    background-color:  rgb(255, 243, 142);    \n"
"}")
        self.push_deleteUser.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/370858-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.push_deleteUser.setIcon(icon2)
        self.push_deleteUser.setIconSize(QtCore.QSize(175, 175))
        self.push_deleteUser.setObjectName("push_deleteUser")
        self.horizontalLayout_6.addWidget(self.push_deleteUser)
        self.verticalLayout_3.addWidget(self.ICON_S)
        self.del_name = QtWidgets.QFrame(self.dell_user)
        self.del_name.setStyleSheet("QFrame{\n"
"    border: 0px;\n"
"}")
        self.del_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.del_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.del_name.setObjectName("del_name")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.del_name)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.del_name)
        self.label_3.setStyleSheet("QLabel{\n"
"color: rgb(28,191,255);\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_3.addWidget(self.del_name)
        self.horizontalLayout.addWidget(self.dell_user)
        BiometricVoice.setCentralWidget(self.centralwidget)

        self.retranslateUi(BiometricVoice)
        QtCore.QMetaObject.connectSlotsByName(BiometricVoice)

    def retranslateUi(self, BiometricVoice):
        _translate = QtCore.QCoreApplication.translate
        BiometricVoice.setWindowTitle(_translate("BiometricVoice", "MainWindow"))
        self.label.setText(_translate("BiometricVoice", "ADD USER"))
        self.label_2.setText(_translate("BiometricVoice", "SEARCH USER"))
        self.label_3.setText(_translate("BiometricVoice", "DELETE USER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BiometricVoice = QtWidgets.QMainWindow()
    ui = Ui_BiometricVoice()
    ui.setupUi(BiometricVoice)
    BiometricVoice.show()
    sys.exit(app.exec_())
